version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nba-postgres
    environment:
      POSTGRES_DB: nbastats
      POSTGRES_USER: nbauser
      POSTGRES_PASSWORD: nbapass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nba-net

  app:
    build: .
    container_name: nba-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nbastats
      SPRING_DATASOURCE_USERNAME: nbauser
      SPRING_DATASOURCE_PASSWORD: nbapass
    networks:
      - nba-net

volumes:
  postgres_data:

networks:
  nba-net: