spring:
  datasource:
    url: jdbc:postgresql://db:5432/nbastats
    username: nbauser
    password: nbapass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080